CREATE PROC FI_SP_AltBeneficiario
    @NOME          VARCHAR (50) ,    
	@CPF          VARCHAR(14),
	@IDCLIENTE    BIGINT
AS
BEGIN
	UPDATE BENEFICIARIO 
	SET 
		NOME = @NOME, 
		IDCLIENTE = @IDCLIENTE
		
	WHERE CPF = @CPF
END