USE [Teste]
GO

/****** Object:  Table [dbo].[Fornecedores]    Script Date: 18/10/2024 11:35:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clientes](
	[Id] [bigint] NOT NULL,
	NOME          VARCHAR (50) NOT NULL,
    SOBRENOME     VARCHAR (255) NOT NULL,
    NACIONALIDADE VARCHAR (50) NOT NULL,
    CEP           VARCHAR (9) NOT NULL,
    ESTADO        VARCHAR (2)  NOT NULL,
    CIDADE        VARCHAR (50) NOT NULL,
    LOGRADOURO    VARCHAR (500) NOT NULL,
    EMAIL         VARCHAR (2079),
    TELEFONE      VARCHAR (15),
    CPF           VARCHAR (14) NOT NULL	
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


