USE [Teste]
GO

/****** Object:  Table [dbo].[Beneficiario]    Script Date: 20/10/2024 20:18:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Beneficiario](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[IIDCLIENTE] [bigint] NULL,
	[CPF] [varchar](14) NOT NULL,
 CONSTRAINT [PK_Beneficiario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


